version: "3.9"
services:
  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/migros?useSSL=false
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - db
    volumes:
      - $HOME/.m2:/root/.m2
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: migros
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    healthcheck:
      test: "/usr/bin/mysql --user=myuser --password=mypassword --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10